### ISSUE TITLE
Google Colaboratory

### ISSUE THREAD

**Issue by nestordemeure** [argonne-lcf/ATPESC_MachineLearning#4]
The repository's readme refer to the possibility of using [Google's Colaboratory Platform](https://colab.research.google.com/) but the 00_statisticalLearning notebook use local datasets and functions making it impossible to use them as-is in Google Colab.

**Comment by felker** [comment]
https://github.com/argonne-lcf/ATPESC_MachineLearning/releases/tag/2021

The 2021 stats notebook is fully compatible with Colab. The deep learning notebooks from 2021 and this year are also compatible. @saforem2 's changes to the stats notebook to run on Polaris are incompatible with Colab, as you point out. I will add comments clarifying this, thanks!

**Comment by saforem2** [comment]
I updated [00_statisticalLearning/README.md](https://github.com/argonne-lcf/ATPESC_MachineLearning/tree/master/00_statisticalLearning)

Detailed instructions for getting it running can also be found in the accompanying [slides](https://saforem2.github.io/ATPESC-StatisticalLearning/#/)

happy to close this if that resolves everything?
